version: 2.1

orbs:
  node: circleci/node@5.2.0

executor_node: &executor_node
  executor:
    name: node/default
    tag: "22.17.0"
  resource_class: small

parameters:
  node_modules_cache_key:
    type: string
    default: v2-dependencies-{{ checksum "package-lock.json" }}

commands:
  restore_cache_node_modules:
    steps:
      - restore_cache:
          name: Restore cached node_modules/
          keys:
            - << pipeline.parameters.node_modules_cache_key >>

  save_cache_node_modules:
    steps:
      - save_cache:
          paths:
            - node_modules
          key: << pipeline.parameters.node_modules_cache_key >>

  save_cache_build:
    steps:
      - save_cache:
          name: Save build folder to cache
          key: build--{{ .Revision }}
          paths:
            - build

  restore_cache_build:
    steps:
      - restore_cache:
          name: Restore build folder from cache
          keys:
            - build--{{ .Revision }}

jobs:
  start_build:
    type: no-op

  complete_build:
    <<: *executor_node
    steps:
      - run:
          name: "Complete build"
          command: echo "Build completed successfully"

  lint_and_test:
    <<: *executor_node
    steps:
      - checkout
      - restore_cache_node_modules
      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache_node_modules
      - run:
          name: "Test"
          command: npm run test
      - run:
          name: "Build"
          command: npm run build
      - run:
          name: Report uncommitted changes produced by the build, failing if any exist
          command: UNCOMMITTED=$(git status --untracked-files=no --porcelain) && echo "$UNCOMMITTED" && [ -z "$UNCOMMITTED" ]
      - run:
          name: Dry-run a semantic-release to confirm no issues upon merge
          command: npx semantic-release --dry-run


  publish_release:
    <<: *executor_node
    steps:
      - checkout
      - restore_cache_node_modules
      - run:
          name: Generate documentation
          command: npm run build
      - run:
          name: Configure dependencies
          command: |
            git config user.email "talisaspire@technologyfromsage.com"
            git config user.name "talisaspire"
      - run:
          name: Deploy docs to github pages
          command: npm run publish:githubpages
      - run:
          name: Release to npm and Github
          command: npx semantic-release

workflows:
  build-and-test:
    jobs:
      - start_build
      - be_kind_to_your_colleagues:
          type: approval
          filters:
            branches:
              ignore:
                - main
      - lint_and_test:
          requires:
            - start_build
            - be_kind_to_your_colleagues
      - publish_release:
          requires:
            - lint_and_test
          filters:
            branches:
              only:
                - main
      - complete_build:
          requires:
            - lint_and_test
            - publish_release
